### ISSUE TITLE
Partner logos not loading

### ISSUE THREAD

**Issue by palcu** [rosedu/site#65]
On the [partners](http://www.rosedu.org/partners/) page, some logos are not loading.

![screen shot 2015-03-01 at 22 51 55](https://cloud.githubusercontent.com/assets/772220/6432763/93fc48fc-c065-11e4-86f2-d1d1729533ab.png)

Thanks @sorinasandu for spotting this

**Comment by tudalex** [comment]
This happens because the logos we're loaded from the CDL website!

**Comment by maria** [comment]
:+1: solved
