### ISSUE TITLE
Update files sections

### ISSUE THREAD

**Issue by maria** [rosedu/site#67]
### Problem

@eminemix found an incomplete version of our status at the URL http://www.rosedu.org/files/Asociatia_ROSEdu_Statut.pdf
which points to https://github.com/rosedu/site/blob/master/files/Asociatia_ROSEdu_Statut.pdf

That document is not the same with https://docs.google.com/document/u/2/d/1dNK9OBY0ilfq68GscWe9auYFkmJy5_w1N1qdciTw5b0/pub which we link in our website.

### Solution

Update files on Github :)

**Comment by eminemix** [comment]
Would it be reasonable to export that google drive file as a pdf and replace it? Or we just want to delete the outdated file?

**Comment by maria** [comment]
@eminemix just delete it, please.
