### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by valenting** [rosedu/site#68]
A license needs to be chosen for this repo.
All contributors need to agree with the chosen license.
A list of contributors is enclosed below:
- [ ] Alex Eftimie @alexef
- [ ] Razvan Deaconescu @razvand
- [ ] Flavius Anton @flaviusanton
- [ ] Marius Coțofană @mariuscoto
- [ ] Maria Niță @maria
- [ ] Camelia Groza @camelia-groza
- [ ] Tudorica Constantin-Alexandru @tudalex
- [ ] Dan Serban @dserban
- [ ] Mihai Maruseac @mihaimaruseac
- [ ] Alex Morega @mgax
- [ ] Cătălin Mariș @alrra
- [ ] Laura Mihaela Vasilescu @lauravasilescu
- [ ] @alexandrujuncu
- [ ] Mihnea Dobrescu-Balaur @mihneadb
- [ ] Adrian Scoica @adriansc
- [ ] Silviu-Mihai Popescu @silviupopescu
- [ ] Victor Cărbune @vcarbune
- [ ] Vlad Dogaru @ddvlad

(This message was generated automatically.)

**Comment by dserban** [comment]
The top portion of:
resources/promo/webdev_promo_banner.png
(i.e. the WebDev logo) is Creative-Commons-licensed (CC-BY-NC with clarifications).

**Comment by maria** [comment]
The issue was created with a script, it doesn't represent a plan or action which will take place. We will close them for now and open new issues when all legal matter are in order. Thank you!
